services:
  docs:
    container_name: wealthvn-docs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    command: pnpm serve --host 0.0.0.0 --port 3010
    restart: unless-stopped
    # If you want to run in development mode with hot-reload, uncomment the following lines:
    # command: pnpm start --host 0.0.0.0 --port 3010
    # volumes:
    #   - .:/app
    #   - /app/node_modules
